pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout your GitHub repo
                git branch: 'main', url: 'https://github.com/karthik-tenali/Jenkins.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Change into mywebsite folder to find Dockerfile
                    dir('mywebsite') {
                        docker.build("mywebsite:latest")
                    }
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    // Stop and remove any previously running container named 'mywebsite'
                    sh '''
                        if [ $(docker ps -q -f name=mywebsite) ]; then
                            docker stop mywebsite
                        fi
                        if [ $(docker ps -a -q -f name=mywebsite) ]; then
                            docker rm mywebsite
                        fi
                    '''

                    // Run the Docker container on port 8081
                    sh 'docker run -d -p 8081:80 --name mywebsite mywebsite:latest'
                }
            }
        }
    }
}

