pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/karthik-tenali/Jenkins.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("mywebsite:latest")
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    docker.image("mywebsite:latest").run('-p 8081:80')
                }
            }
        }
    }
}

